### ISSUE TITLE
Errors in the console in the latest Firefox Release (v29)

### ISSUE THREAD

**Issue by Drugoy** [fwenzel/imagetwist#13]
```
Exception {message: "", result: 2153644038, name: "", filename: "resource://gre/modules/XPIProvider.jsm -> jar:file:///C:/path/to/Firefox/Data/profile/extensions/jid1-4p5x9fY6wqtuqA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-4p5x9fy6wqtuqa-at-jetpack/imagetwist/data/js/exif-js/binaryajax.js", lineNumber: 205, columnNumber: 0, inner: null, data: null} timers.js:43
Exception {message: "", result: 2153644038, name: "", filename: "resource://gre/modules/XPIProvider.jsm -> jar:file:///C:/path/to/Firefox/Data/profile/extensions/jid1-4p5x9fY6wqtuqA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-4p5x9fy6wqtuqa-at-jetpack/imagetwist/data/js/exif-js/binaryajax.js", lineNumber: 205, columnNumber: 0, inner: null, data: null} timers.js:43
```

I'm using latest Fx stable version (v29) and imagetwist v1.1.

**Comment by fwenzel** [comment]
Thank you for filing! I'll check but I think Firefox 29 ships this functionality by itself, so I should probably just make it incompatible with Firefox 29 and up? What do you think?

**Comment by fwenzel** [comment]
Actually I tried with Fx29 and my example image (the Mona Lisa) is **not** automatically flipped.

**Comment by Drugoy** [comment]
Flipping that was added to firefox is only working for photos with EXIF data and only if those data contain the info about whether the photo was taken in the landscape mode or not.
Most of pictures in the internet don't have any EXIF data at all.

**Comment by fwenzel** [comment]
Ah right, sorry I was misunderstanding you. Yes it's broken on latest versions of Firefox, I will fix and resubmit!

**Comment by Drugoy** [comment]
Thank you. I'll keep tracking this issue and will re-enable your add-on whenever you release a beta version or if add-ons manager will suggest me an update.

**Comment by Drugoy** [comment]
It's a pity you abandoned your extension :(

**Comment by fwenzel** [comment]
Latest versions of Firefox do it automatically don't they?

**Comment by Drugoy** [comment]
Firefox rotates them automatically based on some metadata. This only works for photos with those data. It's like 0.1% of the pictures in the interwebs.

**Comment by fwenzel** [comment]
Oh, that's a good point of course.
